version: '3'

includes:
  engine:
    taskfile: ./engine/taskfile.yaml
    dir: ./engine
  sdk:
    taskfile: ./sdk/taskfile.yaml
    dir: ./sdk

vars:
  DB:
    map:
      commons: postgres

tasks:
  sources:
    aliases: [src]
    desc: Build all sources if checks passed
    cmds:
      - task: engine:sources
      - task: sdk:sources

  binaries:
    aliases: [bins]
    desc: Build all binaries if checks passed
    cmds:
      - task: engine:binaries

  distros:
    desc: Build all distros if checks passed
    deps:
      - task: engine:tests:it
      - task: sdk:tests
    cmds:
      - cmd: docker buildx bake

  stack:*:
    desc: Build specified stack if checks passed
    cmds:
      - task: stand:{{index .MATCH 0}}
      - task: engine:tests:e2e
      - cmd: echo stack were built

  stand:*:
    desc: Start specified stand
    vars:
      OPS: '{{index .MATCH 0}}'
    dir: stack
    cmds:
      - cmd: >-
          docker compose
          --file ops/{{index .DB .OPS}}.compose.yaml
          --file ops/engine.compose.yaml
          --env-file ops/{{.OPS}}/.env
          up
          --remove-orphans
          --pull missing
          --quiet-pull
          --detach
