version: '3'

includes:
  engine:
    taskfile: ./go-engine/taskfile.yaml
    dir: ./go-engine
  sdk:
    taskfile: ./go-sdk/taskfile.yaml
    dir: ./go-sdk
  stack:
    taskfile: ./stack/taskfile.yaml
    dir: ./stack

tasks:
  sources:
    aliases: [src]
    desc: Check all sources
    cmds:
      - task: engine:sources
      - task: sdk:sources

  binaries:
    aliases: [bins]
    desc: Build all binaries if checks passed
    cmds:
      - task: engine:binaries

  packages:
    aliases: [pkgs]
    desc: Build all packages if checks passed
    deps:
      - task: engine:tests
        vars:
          LVL: it
      - task: sdk:tests
        vars:
          LVL: it
    cmds:
      - cmd: docker buildx bake

  stack:
    desc: Build specified stack if checks passed
    deps:
      - task: engine:tests
        vars:
          LVL: e2e
    cmds:
      - cmd: echo stacks were built
