---
name: Chekout repos
description: Chekout repos
runs:
  using: "composite"
  steps:
    - name: Checkout sdk repo
      uses: actions/checkout@v6
      with:
        repository: orglang/go-sdk
        path: sdk
    - name: Checkout engine repo
      uses: actions/checkout@v6
      with:
        repository: orglang/go-engine
        path: engine
