---
name: Setup gear
description: Setup gear
runs:
  using: "composite"
  steps:
    - name: Setup go
      uses: actions/setup-go@v6.2.0
      with:
        go-version: '1.25'
    - name: Setup task
      uses: go-task/setup-task@v1
